import { Inject, Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../../infra/prisma/prisma.service';
import {
  NOTIFICATION_PROVIDER,
  type NotificationProvider,
} from '../../../push/notification-provider.interface';

export type MatchNotificationType =
  | 'invited'
  | 'promoted'
  | 'reconfirm_required'
  | 'canceled'
  | 'match_started'
  | 'reminder_missing_players'
  | 'missing_players_alert'
  | 'teams_auto_generated'
  | 'reminder_24h'
  | 'reminder_2h';

const COOLDOWN_MS: Partial<Record<MatchNotificationType, number>> = {
  invited: 30 * 60 * 1000,
  promoted: 5 * 60 * 1000,
  reconfirm_required: 60 * 60 * 1000,
  canceled: 60 * 60 * 1000,
  match_started: 60 * 60 * 1000,
  missing_players_alert: 5 * 60 * 1000,
  teams_auto_generated: 60 * 60 * 1000,
  // reminder_missing_players, reminder_24h, reminder_2h use bucket-based dedup (no time-window cooldown)
};

export interface OnInvitedInput {
  matchId: string;
  matchTitle: string;
  invitedUserId: string;
}

export interface OnPromotedInput {
  matchId: string;
  matchTitle: string;
  promotedUserId: string;
}

export interface OnReconfirmRequiredInput {
  matchId: string;
  matchTitle: string;
  userIds: string[];
}

export interface OnCanceledInput {
  matchId: string;
  matchTitle: string;
  userIds: string[];
  actorId: string | null;
}

export interface OnReminderMissingPlayersInput {
  matchId: string;
  matchTitle: string;
  userIds: string[];
  missingCount: number;
  minutesToStart: number;
  bucket: string;
}

export interface OnMatchStartedInput {
  matchId: string;
  matchTitle: string;
  userIds: string[];
}

export interface OnMissingPlayersAlertInput {
  matchId: string;
  matchTitle: string;
  userIds: string[];
  missingCount: number;
  minutesToStart: number;
}

export interface OnTeamsAutoGeneratedInput {
  matchId: string;
  matchTitle: string;
  creatorId: string;
}

@Injectable()
export class MatchNotificationService {
  private readonly logger = new Logger(MatchNotificationService.name);

  constructor(
    private readonly prisma: PrismaService,
    @Inject(NOTIFICATION_PROVIDER)
    private readonly provider: NotificationProvider,
  ) {}

  async onInvited(input: OnInvitedInput): Promise<void> {
    const { matchId, matchTitle, invitedUserId } = input;
    if (!(await this.shouldSend(invitedUserId, matchId, 'invited'))) return;

    await this.provider.sendToUser(invitedUserId, {
      title: 'Te invitaron a un partido',
      body: `Fuiste invitado a "${matchTitle}".`,
      data: { type: 'invited', matchId },
    });

    await this.recordDelivery(invitedUserId, matchId, 'invited');
  }

  async onPromoted(input: OnPromotedInput): Promise<void> {
    const { matchId, matchTitle, promotedUserId } = input;
    if (!(await this.shouldSend(promotedUserId, matchId, 'promoted'))) return;

    await this.provider.sendToUser(promotedUserId, {
      title: '¡Tenés lugar confirmado!',
      body: `Saliste de la lista de espera en "${matchTitle}".`,
      data: { type: 'promoted', matchId },
    });

    await this.recordDelivery(promotedUserId, matchId, 'promoted');
  }

  async onReconfirmRequired(input: OnReconfirmRequiredInput): Promise<void> {
    const { matchId, matchTitle, userIds } = input;

    await Promise.allSettled(
      userIds.map(async (userId) => {
        if (!(await this.shouldSend(userId, matchId, 'reconfirm_required')))
          return;

        await this.provider.sendToUser(userId, {
          title: 'Reconfirmación requerida',
          body: `Hubo cambios importantes en "${matchTitle}". Por favor reconfirmá tu participación.`,
          data: { type: 'reconfirm_required', matchId },
        });

        await this.recordDelivery(userId, matchId, 'reconfirm_required');
      }),
    );
  }

  async onCanceled(input: OnCanceledInput): Promise<void> {
    const { matchId, matchTitle, userIds, actorId } = input;
    // actorId == null means system cancel → notify all; otherwise skip the actor
    const targets =
      actorId !== null ? userIds.filter((id) => id !== actorId) : userIds;

    const body =
      actorId !== null
        ? `"${matchTitle}" fue cancelado por el organizador.`
        : `"${matchTitle}" fue cancelado automáticamente por falta de jugadores.`;

    await Promise.allSettled(
      targets.map(async (userId) => {
        if (!(await this.shouldSend(userId, matchId, 'canceled'))) return;

        await this.provider.sendToUser(userId, {
          title: 'Partido cancelado',
          body,
          data: { type: 'canceled', matchId },
        });

        await this.recordDelivery(userId, matchId, 'canceled');
      }),
    );
  }

  async onReminderMissingPlayers(
    input: OnReminderMissingPlayersInput,
  ): Promise<void> {
    const {
      matchId,
      matchTitle,
      userIds,
      missingCount,
      minutesToStart,
      bucket,
    } = input;

    await Promise.allSettled(
      userIds.map(async (userId) => {
        if (
          !(await this.shouldSend(
            userId,
            matchId,
            'reminder_missing_players',
            bucket,
          ))
        )
          return;

        await this.provider.sendToUser(userId, {
          title: 'Faltan jugadores',
          body: `Faltan ${missingCount} jugadores para "${matchTitle}" (${Math.round(minutesToStart)} min).`,
          data: { type: 'reminder_missing_players', matchId },
        });

        await this.recordDelivery(
          userId,
          matchId,
          'reminder_missing_players',
          bucket,
        );
      }),
    );
  }

  async onMatchStarted(input: OnMatchStartedInput): Promise<void> {
    const { matchId, matchTitle, userIds } = input;

    await Promise.allSettled(
      userIds.map(async (userId) => {
        if (!(await this.shouldSend(userId, matchId, 'match_started'))) return;

        await this.provider.sendToUser(userId, {
          title: '¡El partido comenzó!',
          body: `"${matchTitle}" ya está en juego.`,
          data: { type: 'match_started', matchId },
        });

        await this.recordDelivery(userId, matchId, 'match_started');
      }),
    );
  }

  async onMissingPlayersAlert(
    input: OnMissingPlayersAlertInput,
  ): Promise<void> {
    const { matchId, matchTitle, userIds, missingCount, minutesToStart } =
      input;

    await Promise.allSettled(
      userIds.map(async (userId) => {
        if (!(await this.shouldSend(userId, matchId, 'missing_players_alert')))
          return;

        await this.provider.sendToUser(userId, {
          title: 'Se bajó un jugador',
          body: `Faltan ${missingCount} jugadores para "${matchTitle}" (${Math.round(minutesToStart)} min).`,
          data: { type: 'missing_players_alert', matchId },
        });

        await this.recordDelivery(userId, matchId, 'missing_players_alert');
      }),
    );
  }

  /**
   * Notify creator + all match admins that a player left or was kicked and the
   * match is now under capacity. Handles admin lookup internally so callers
   * don't duplicate that query.
   */
  async onMissingPlayersAlertWithLookup(input: {
    matchId: string;
    matchTitle: string;
    creatorId: string;
    confirmedCount: number;
    capacity: number;
    minutesToStart: number;
  }): Promise<void> {
    const {
      matchId,
      matchTitle,
      creatorId,
      confirmedCount,
      capacity,
      minutesToStart,
    } = input;
    const missingCount = capacity - confirmedCount;
    if (missingCount <= 0) return;

    const adminRows = await this.prisma.client.matchParticipant.findMany({
      where: { matchId, isMatchAdmin: true },
      select: { userId: true },
    });
    const recipientIds = [
      ...new Set([creatorId, ...adminRows.map((r) => r.userId)]),
    ];

    await this.onMissingPlayersAlert({
      matchId,
      matchTitle,
      userIds: recipientIds,
      missingCount,
      minutesToStart,
    });
  }

  async onTeamsAutoGenerated(input: OnTeamsAutoGeneratedInput): Promise<void> {
    const { matchId, matchTitle, creatorId } = input;
    if (!(await this.shouldSend(creatorId, matchId, 'teams_auto_generated')))
      return;

    await this.provider.sendToUser(creatorId, {
      title: 'Equipos generados automáticamente',
      body: `Los equipos de "${matchTitle}" fueron armados automáticamente. Podés editarlos antes del partido.`,
      data: { type: 'teams_auto_generated', matchId },
    });

    await this.recordDelivery(creatorId, matchId, 'teams_auto_generated');
  }

  async onReminder24h(input: {
    matchId: string;
    matchTitle: string;
    userIds: string[];
  }): Promise<void> {
    await this.sendTimedReminder(
      'reminder_24h',
      't24h',
      input.userIds,
      input.matchId,
      'Tu partido es mañana',
      `"${input.matchTitle}" comienza en ~24 horas.`,
      { type: 'reminder_24h', matchId: input.matchId },
    );
  }

  async onReminder2h(input: {
    matchId: string;
    matchTitle: string;
    userIds: string[];
  }): Promise<void> {
    await this.sendTimedReminder(
      'reminder_2h',
      't2h',
      input.userIds,
      input.matchId,
      '¡Tu partido está por empezar!',
      `"${input.matchTitle}" comienza en 2 horas. ¡Preparate!`,
      { type: 'reminder_2h', matchId: input.matchId },
    );
  }

  private async sendTimedReminder(
    type: 'reminder_24h' | 'reminder_2h',
    bucket: string,
    userIds: string[],
    matchId: string,
    title: string,
    body: string,
    data: Record<string, unknown>,
  ): Promise<void> {
    await Promise.allSettled(
      userIds.map(async (userId) => {
        if (!(await this.shouldSend(userId, matchId, type, bucket))) return;

        await this.provider.sendToUser(userId, { title, body, data });

        await this.recordDelivery(userId, matchId, type, bucket);
      }),
    );
  }

  private async shouldSend(
    userId: string,
    matchId: string,
    type: MatchNotificationType,
    bucket?: string,
  ): Promise<boolean> {
    if (bucket !== undefined) {
      // Bucket-based dedup: one notification per (userId, matchId, type, bucket)
      const existing = await this.prisma.client.notificationDelivery.findFirst({
        where: { userId, matchId, type, bucket },
      });
      return existing === null;
    }

    const cooldownMs = COOLDOWN_MS[type];
    if (cooldownMs === undefined) return true;
    const since = new Date(Date.now() - cooldownMs);

    const existing = await this.prisma.client.notificationDelivery.findFirst({
      where: { userId, matchId, type, createdAt: { gte: since } },
    });

    return existing === null;
  }

  private async recordDelivery(
    userId: string,
    matchId: string,
    type: MatchNotificationType,
    bucket?: string,
  ): Promise<void> {
    await this.prisma.client.notificationDelivery.create({
      data: {
        userId,
        matchId,
        type,
        ...(bucket !== undefined ? { bucket } : {}),
      },
    });
  }
}
