import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../../../infra/prisma/prisma.service';
import { REDIS_CLIENT } from '../../../infra/redis/redis.module';
import { lockMatchRow } from '../shared/lock-match-row';
import { MatchAuditService, AuditLogType } from '../audit/match-audit.service';
import type { OnTeamsAutoGeneratedInput } from '../notifications/match-notification.service';
import { MatchNotificationService } from '../notifications/match-notification.service';
import { MatchRealtimePublisher } from '../../realtime/match-realtime.publisher';
import type Redis from 'ioredis';

const ONE_HOUR_MS = 60 * 60 * 1000;

// Safety cap: process at most this many overdue matches per tick to avoid
// overwhelming the DB on first deploy with a large backlog.
const OVERDUE_BATCH_LIMIT = 50;

type MatchWithParticipants = {
  id: string;
  title: string;
  startsAt: Date;
  capacity: number;
  status: string;
  revision: number;
  isLocked: boolean;
  createdById: string;
  teamsConfigured: boolean;
  teamsAutoGenBlocked: boolean;
  participants: Array<{
    userId: string;
    status: string;
    isMatchAdmin: boolean;
  }>;
};

@Injectable()
export class MatchLifecycleJob {
  private readonly logger = new Logger(MatchLifecycleJob.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: MatchAuditService,
    private readonly matchNotification: MatchNotificationService,
    private readonly realtimePublisher: MatchRealtimePublisher,
    @Optional() @Inject(REDIS_CLIENT) private readonly redis: Redis | null,
  ) {}

  @Cron(CronExpression.EVERY_MINUTE)
  async runTick(): Promise<void> {
    if (this.redis) {
      void this.redis.set('lifecycle:lastTickAt', new Date().toISOString(), 'EX', 120).catch(() => undefined);
    }

    const now = new Date();
    const upcomingWindowEnd = new Date(now.getTime() + 60 * 60 * 1000);

    // T-24h window: 23–25h before start (2h wide to ensure full coverage at 1-min cadence)
    const window24hStart = new Date(now.getTime() + 23 * 60 * 60 * 1000);
    const window24hEnd = new Date(now.getTime() + 25 * 60 * 60 * 1000);

    // T-2h window: 1.5–2.5h before start
    const window2hStart = new Date(now.getTime() + 90 * 60 * 1000);
    const window2hEnd = new Date(now.getTime() + 150 * 60 * 1000);

    const [
      upcomingMatches,
      overdueMatches,
      inProgressMatches,
      reminder24hMatches,
      reminder2hMatches,
    ] = await Promise.all([
      // Future matches within the next 60min: candidates for auto-lock and reminders.
      // Lower bound is now (exclusive) so only pre-start matches are included.
      this.prisma.client.match.findMany({
        where: {
          startsAt: { gt: now, lte: upcomingWindowEnd },
          status: { in: ['scheduled', 'locked'] },
        },
        include: {
          participants: {
            select: { userId: true, status: true, isMatchAdmin: true },
          },
        },
      }),

      // Overdue matches: startsAt is in the past, still scheduled/locked.
      // NO lower bound — catches ALL stale matches regardless of age.
      // Ordered oldest-first so the backlog clears consistently.
      // Batch-limited to avoid thundering-herd on first run after a long gap.
      this.prisma.client.match.findMany({
        where: {
          startsAt: { lte: now },
          status: { in: ['scheduled', 'locked'] },
        },
        orderBy: { startsAt: 'asc' },
        take: OVERDUE_BATCH_LIMIT,
        include: {
          participants: {
            select: { userId: true, status: true, isMatchAdmin: true },
          },
        },
      }),

      // In-progress matches that may be ready to finalize as played.
      this.prisma.client.match.findMany({
        where: { status: 'in_progress' },
        include: {
          participants: {
            select: { userId: true, status: true, isMatchAdmin: true },
          },
        },
      }),

      // T-24h reminder window: matches starting in 23–25h.
      this.prisma.client.match.findMany({
        where: {
          startsAt: { gt: window24hStart, lte: window24hEnd },
          status: { in: ['scheduled', 'locked'] },
        },
        include: {
          participants: {
            select: { userId: true, status: true, isMatchAdmin: true },
          },
        },
      }),

      // T-2h reminder window: matches starting in 1.5–2.5h.
      this.prisma.client.match.findMany({
        where: {
          startsAt: { gt: window2hStart, lte: window2hEnd },
          status: { in: ['scheduled', 'locked'] },
        },
        include: {
          participants: {
            select: { userId: true, status: true, isMatchAdmin: true },
          },
        },
      }),
    ]);

    await Promise.allSettled([
      ...upcomingMatches.map((match) =>
        this.processUpcoming(match as MatchWithParticipants, now),
      ),
      ...overdueMatches.map((match) =>
        this.processOverdue(match as MatchWithParticipants, now),
      ),
      ...inProgressMatches.map((match) =>
        this.tryFinalizeMatch(match as MatchWithParticipants, now),
      ),
      ...reminder24hMatches.map((match) =>
        this.sendTimedReminder(match as MatchWithParticipants, 'reminder_24h'),
      ),
      ...reminder2hMatches.map((match) =>
        this.sendTimedReminder(match as MatchWithParticipants, 'reminder_2h'),
      ),
    ]);
  }

  private async sendTimedReminder(
    match: MatchWithParticipants,
    type: 'reminder_24h' | 'reminder_2h',
  ): Promise<void> {
    const confirmedUserIds = match.participants
      .filter((p) => p.status === 'CONFIRMED')
      .map((p) => p.userId);

    if (confirmedUserIds.length === 0) return;

    try {
      if (type === 'reminder_24h') {
        await this.matchNotification.onReminder24h({
          matchId: match.id,
          matchTitle: match.title,
          userIds: confirmedUserIds,
        });
      } else {
        await this.matchNotification.onReminder2h({
          matchId: match.id,
          matchTitle: match.title,
          userIds: confirmedUserIds,
        });
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] ${type} reminder failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  /**
   * Handles matches that have NOT started yet (startsAt > now) and are
   * within the next 60 minutes.
   * - Auto-lock when full
   * - Send reminder when not full
   */
  private async processUpcoming(
    match: MatchWithParticipants,
    now: Date,
  ): Promise<void> {
    const minutesToStart = (match.startsAt.getTime() - now.getTime()) / 60_000;
    const confirmedCount = match.participants.filter(
      (p) => p.status === 'CONFIRMED',
    ).length;
    const isFull = confirmedCount >= match.capacity;

    if (isFull && !match.isLocked) {
      await this.autoLock(match);
    }

    if (!isFull) {
      await this.sendReminder(match, confirmedCount, minutesToStart);
    }

    if (
      minutesToStart <= 30 &&
      !match.teamsConfigured &&
      !match.teamsAutoGenBlocked
    ) {
      await this.autoGenerateTeams(match);
    }
  }

  /**
   * Handles matches that are past their startsAt and still scheduled/locked.
   * - Full → in_progress (or played directly if job ran >60min late)
   * - Not full → canceled
   * No window constraint — any stale match is reconciled here.
   */
  private async processOverdue(
    match: MatchWithParticipants,
    now: Date,
  ): Promise<void> {
    const confirmedCount = match.participants.filter(
      (p) => p.status === 'CONFIRMED',
    ).length;
    const isFull = confirmedCount >= match.capacity;

    if (isFull) {
      const isLate = now.getTime() >= match.startsAt.getTime() + ONE_HOUR_MS;
      await this.autoStart(match, isLate);
    } else {
      await this.autoCancel(match);
    }
  }

  private async autoGenerateTeams(match: MatchWithParticipants): Promise<void> {
    try {
      let newRevision: number | null = null;
      let notifyInput: OnTeamsAutoGeneratedInput | null = null;

      await this.prisma.client.$transaction(async (tx) => {
        await lockMatchRow(tx, match.id);

        const fresh = await tx.match.findUnique({ where: { id: match.id } });
        // Idempotency guards — re-check inside the transaction
        if (!fresh || fresh.teamsConfigured || fresh.teamsAutoGenBlocked)
          return;
        if (['canceled', 'played', 'in_progress'].includes(fresh.status))
          return;

        const confirmedRows = await tx.matchParticipant.findMany({
          where: { matchId: match.id, status: 'CONFIRMED' },
          select: { userId: true },
        });

        // Need at least one player to form slots
        if (confirmedRows.length === 0) return;

        const slotsPerTeam = Math.floor(fresh.capacity / 2);
        const players = confirmedRows.map((r) => r.userId);

        // Fisher-Yates shuffle
        for (let i = players.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [players[i], players[j]] = [players[j], players[i]] as [
            string,
            string,
          ];
        }

        const teamAPlayers = players.slice(0, slotsPerTeam);
        const teamBPlayers = players.slice(slotsPerTeam, slotsPerTeam * 2);

        const slotData = [
          ...Array.from({ length: slotsPerTeam }, (_, i) => ({
            matchId: match.id,
            team: 'A',
            slotIndex: i,
            userId: teamAPlayers[i] ?? null,
          })),
          ...Array.from({ length: slotsPerTeam }, (_, i) => ({
            matchId: match.id,
            team: 'B',
            slotIndex: i,
            userId: teamBPlayers[i] ?? null,
          })),
        ];

        await tx.matchTeamSlot.deleteMany({ where: { matchId: match.id } });
        await tx.matchTeamSlot.createMany({ data: slotData });

        const updated = await tx.match.update({
          where: { id: match.id },
          data: { teamsConfigured: true, revision: fresh.revision + 1 },
        });

        await this.audit.log(
          tx,
          match.id,
          null,
          AuditLogType.MATCH_AUTO_TEAMS_GENERATED,
          { confirmedCount: confirmedRows.length, slotsPerTeam },
        );

        newRevision = updated.revision;
        notifyInput = {
          matchId: match.id,
          matchTitle: match.title,
          creatorId: match.createdById,
        };
      });

      if (newRevision !== null && notifyInput !== null) {
        this.realtimePublisher.notifyMatchUpdated(match.id, newRevision);
        this.logger.log(
          `[MatchLifecycle] Auto-generated teams for match ${match.id}`,
        );

        void this.matchNotification
          .onTeamsAutoGenerated(notifyInput)
          .catch((err: unknown) =>
            this.logger.warn(
              `[MatchLifecycle] onTeamsAutoGenerated notification failed for match ${match.id}: ${(err as Error)?.message}`,
            ),
          );
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Auto-generate teams failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  private async autoLock(match: MatchWithParticipants): Promise<void> {
    try {
      const newRevision = await this.prisma.client.$transaction(async (tx) => {
        await lockMatchRow(tx, match.id);

        const fresh = await tx.match.findUnique({ where: { id: match.id } });
        if (!fresh || fresh.isLocked || fresh.status === 'canceled')
          return null;

        const confirmedCount = await tx.matchParticipant.count({
          where: { matchId: match.id, status: 'CONFIRMED' },
        });
        if (confirmedCount < match.capacity) return null;

        const updated = await tx.match.update({
          where: { id: match.id },
          data: {
            isLocked: true,
            lockedAt: new Date(),
            lockedBy: null,
            revision: fresh.revision + 1,
          },
        });

        await this.audit.log(
          tx,
          match.id,
          null,
          AuditLogType.MATCH_AUTO_LOCKED,
          { confirmedCount },
        );

        return updated.revision;
      });

      if (newRevision !== null) {
        this.realtimePublisher.notifyMatchUpdated(match.id, newRevision);
        this.logger.log(`[MatchLifecycle] Auto-locked match ${match.id}`);
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Auto-lock failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  private async sendReminder(
    match: MatchWithParticipants,
    confirmedCount: number,
    minutesToStart: number,
  ): Promise<void> {
    try {
      const missingCount = match.capacity - confirmedCount;
      // bucket: 0-14 min = b0, 15-29 = b1, 30-44 = b2, 45-60 = b3
      const bucket = `b${Math.floor(minutesToStart / 15)}`;

      const adminUserIds = match.participants
        .filter((p) => p.isMatchAdmin)
        .map((p) => p.userId);
      const recipientIds = [...new Set([match.createdById, ...adminUserIds])];

      await this.matchNotification.onReminderMissingPlayers({
        matchId: match.id,
        matchTitle: match.title,
        userIds: recipientIds,
        missingCount,
        minutesToStart,
        bucket,
      });
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Reminder failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  /**
   * Transitions a full match at/past startsAt:
   * - Normal: scheduled/locked → in_progress (remove waitlist)
   * - Late reconciliation (job ran >60min late): skip in_progress, go directly to played
   */
  private async autoStart(
    match: MatchWithParticipants,
    isLate: boolean,
  ): Promise<void> {
    try {
      let newRevision: number | null = null;
      let confirmedUserIds: string[] = [];

      await this.prisma.client.$transaction(async (tx) => {
        await lockMatchRow(tx, match.id);

        const fresh = await tx.match.findUnique({ where: { id: match.id } });
        // Idempotent: already transitioned by a prior run
        if (
          !fresh ||
          fresh.status === 'canceled' ||
          fresh.status === 'in_progress' ||
          fresh.status === 'played'
        )
          return;

        const confirmedCount = await tx.matchParticipant.count({
          where: { matchId: match.id, status: 'CONFIRMED' },
        });
        // Re-check fullness inside tx — if no longer full, autoCancel should handle it next tick
        if (confirmedCount < match.capacity) return;

        const targetStatus = isLate ? 'played' : 'in_progress';

        const updated = await tx.match.update({
          where: { id: match.id },
          data: { status: targetStatus, revision: fresh.revision + 1 },
        });

        // Remove waitlist — no longer relevant once match is underway
        await tx.matchParticipant.deleteMany({
          where: { matchId: match.id, status: 'WAITLISTED' },
        });

        await this.audit.log(tx, match.id, null, AuditLogType.MATCH_STARTED, {
          confirmedCount,
          targetStatus,
        });

        if (isLate) {
          await this.audit.log(tx, match.id, null, AuditLogType.MATCH_PLAYED, {
            confirmedCount,
            lateReconciliation: true,
          });
        }

        const rows = await tx.matchParticipant.findMany({
          where: { matchId: match.id, status: 'CONFIRMED' },
          select: { userId: true },
        });

        newRevision = updated.revision;
        confirmedUserIds = rows.map((r) => r.userId);
      });

      if (newRevision !== null) {
        this.realtimePublisher.notifyMatchUpdated(match.id, newRevision);
        this.logger.log(
          `[MatchLifecycle] Match ${match.id} started (${isLate ? 'played (late)' : 'in_progress'})`,
        );

        void this.matchNotification
          .onMatchStarted({
            matchId: match.id,
            matchTitle: match.title,
            userIds: confirmedUserIds,
          })
          .catch((err: unknown) =>
            this.logger.warn(
              `[MatchLifecycle] onMatchStarted notification failed for match ${match.id}: ${(err as Error)?.message}`,
            ),
          );
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Auto-start failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  private async autoCancel(match: MatchWithParticipants): Promise<void> {
    try {
      let newRevision: number | null = null;
      let participantUserIds: string[] = [];

      await this.prisma.client.$transaction(async (tx) => {
        await lockMatchRow(tx, match.id);

        const fresh = await tx.match.findUnique({ where: { id: match.id } });
        // Guard against all terminal/in-flight statuses
        if (
          !fresh ||
          fresh.status === 'canceled' ||
          fresh.status === 'played' ||
          fresh.status === 'in_progress'
        )
          return;

        const confirmedCount = await tx.matchParticipant.count({
          where: { matchId: match.id, status: 'CONFIRMED' },
        });
        if (confirmedCount >= match.capacity) return;

        const updated = await tx.match.update({
          where: { id: match.id },
          data: { status: 'canceled', revision: fresh.revision + 1 },
        });

        await this.audit.log(
          tx,
          match.id,
          null,
          AuditLogType.MATCH_AUTO_CANCELED,
          { confirmedCount },
        );

        const rows = await tx.matchParticipant.findMany({
          where: {
            matchId: match.id,
            status: { in: ['CONFIRMED', 'WAITLISTED', 'INVITED', 'SPECTATOR'] },
          },
          select: { userId: true },
        });

        newRevision = updated.revision;
        participantUserIds = rows.map((r) => r.userId);
      });

      if (newRevision !== null) {
        this.realtimePublisher.notifyMatchUpdated(match.id, newRevision);
        this.logger.log(`[MatchLifecycle] Auto-canceled match ${match.id}`);

        void this.matchNotification
          .onCanceled({
            matchId: match.id,
            matchTitle: match.title,
            userIds: participantUserIds,
            actorId: null,
          })
          .catch((err: unknown) =>
            this.logger.warn(
              `[MatchLifecycle] onCanceled notification failed for match ${match.id}: ${(err as Error)?.message}`,
            ),
          );
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Auto-cancel failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }

  /**
   * Transitions in_progress matches to played once 60 minutes have elapsed since startsAt.
   */
  private async tryFinalizeMatch(
    match: MatchWithParticipants,
    now: Date,
  ): Promise<void> {
    const elapsed = now.getTime() - match.startsAt.getTime();
    if (elapsed < ONE_HOUR_MS) return; // not time yet

    try {
      let newRevision: number | null = null;

      await this.prisma.client.$transaction(async (tx) => {
        await lockMatchRow(tx, match.id);

        const fresh = await tx.match.findUnique({ where: { id: match.id } });
        // Idempotent: already finalized
        if (!fresh || fresh.status !== 'in_progress') return;

        const updated = await tx.match.update({
          where: { id: match.id },
          data: { status: 'played', revision: fresh.revision + 1 },
        });

        await this.audit.log(tx, match.id, null, AuditLogType.MATCH_PLAYED, {
          elapsed: Math.round(elapsed / 60_000),
        });

        newRevision = updated.revision;
      });

      if (newRevision !== null) {
        this.realtimePublisher.notifyMatchUpdated(match.id, newRevision);
        this.logger.log(
          `[MatchLifecycle] Match ${match.id} finalized as played`,
        );
      }
    } catch (err: unknown) {
      this.logger.warn(
        `[MatchLifecycle] Finalize failed for match ${match.id}: ${(err as Error)?.message}`,
      );
    }
  }
}
